name: Build EXE with Checksum

on:
  workflow_dispatch:   # you can run manually
  push:
    branches:
      - main           # or whichever branch you want

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole main.py --distpath src --name Chator

      - name: Generate SHA256 checksum
        run: certutil -hashfile src/Chator.exe SHA256 > src/Chator.exe.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Chator-build
          path: |
            src/Chator.exe
            src/Chator.exe.sha256
